package com.wcb.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_account", "id", Account.class);
		arp.addMapping("t_account_equipment", "id", AccountEquipment.class);
		arp.addMapping("t_community", "id", Community.class);
		arp.addMapping("t_district", "id", District.class);
		arp.addMapping("t_district_user", "id", DistrictUser.class);
		arp.addMapping("t_equipment", "id", Equipment.class);
		arp.addMapping("t_prov_city_area_street", "id", ProvCityAreaStreet.class);
		arp.addMapping("t_record_pay", "id", RecordPay.class);
		arp.addMapping("t_record_survey", "id", RecordSurvey.class);
		arp.addMapping("t_sys_dict", "id", Dict.class);
		arp.addMapping("t_sys_func", "id", Func.class);
		arp.addMapping("t_sys_role", "id", Role.class);
		arp.addMapping("t_sys_role_func", "id", RoleFunc.class);
		arp.addMapping("t_sys_user", "id", User.class);
		arp.addMapping("t_sys_user_group", "id", UserGroup.class);
		arp.addMapping("t_sys_user_role", "id", UserRole.class);
	}
}

