package com.wcb.model;

import com.wcb.model.base.BaseAccountEquipment;

/**
 * Generated by JFinal.
 * 水表设备--账户 关系
 */
@SuppressWarnings("serial")
public class AccountEquipment extends BaseAccountEquipment<AccountEquipment> {
	public static final AccountEquipment dao = new AccountEquipment();
}
