package com.wcb.model;

import com.jfinal.plugin.activerecord.Db;
import com.wcb.model.base.BaseAccountEquipment;

/**
 * Generated by JFinal.
 * 水表设备--账户 关系
 */
@SuppressWarnings("serial")
public class AccountEquipment extends BaseAccountEquipment<AccountEquipment> {
    public static final AccountEquipment dao = new AccountEquipment();

    public AccountEquipment getAccountEquipment(Integer accountid, Integer equipmentid) {
        return findFirst("select * from t_account_equipment where accountid = ? and equipmentid = ? and status = 1 ", accountid, equipmentid);
    }

    public void invalidAccountEquipmentByAccountId(Integer accountid) {
        Db.update(" update t_account_equipment set status = 0 where accountid = ? ", accountid);
    }
}
