package com.wcb.model;

import com.wcb.model.base.BaseCommunity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Community extends BaseCommunity<Community> {
	public static final Community dao = new Community();
}
