package com.wcb.model;

import com.wcb.model.base.BaseDistrictUser;

/**
 * Generated by JFinal.
 * 水表账户组 与操作员关系  ---片区授权
 */
@SuppressWarnings("serial")
public class DistrictUser extends BaseDistrictUser<DistrictUser> {
	public static final DistrictUser dao = new DistrictUser();
}
