package com.wcb.model;

import com.wcb.model.base.BaseDistrict;

/**
 * Generated by JFinal.
 * 水表账户 用户组   ---片区
 */
@SuppressWarnings("serial")
public class District extends BaseDistrict<District> {
	public static final District dao = new District();
}
