package com.wcb.model;

import com.wcb.model.base.BaseDistrictUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DistrictUser extends BaseDistrictUser<DistrictUser> {
	public static final DistrictUser dao = new DistrictUser();
}
