package com.wcb.model;

import com.wcb.model.base.BaseDistrict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class District extends BaseDistrict<District> {
	public static final District dao = new District();
}
