package com.wcb.model;

import com.wcb.model.base.BaseEquipment;

/**
 * Generated by JFinal.
 * 水表设备
 */
@SuppressWarnings("serial")
public class Equipment extends BaseEquipment<Equipment> {
	public static final Equipment dao = new Equipment();
}
