package com.wcb.model;

import com.wcb.model.base.BaseFunc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Func extends BaseFunc<Func> {
	public static final Func dao = new Func();
}
