package com.wcb.model;

import com.wcb.model.base.BaseProvCityAreaStreet;

/**
 * Generated by JFinal.
 * 省、市、区
 */
@SuppressWarnings("serial")
public class ProvCityAreaStreet extends BaseProvCityAreaStreet<ProvCityAreaStreet> {
	public static final ProvCityAreaStreet dao = new ProvCityAreaStreet();
}
