package com.wcb.model;

import com.wcb.model.base.BaseProvCityAreaStreet;

import java.util.List;

/**
 * Generated by JFinal.
 * 省、市、区
 */
@SuppressWarnings("serial")
public class ProvCityAreaStreet extends BaseProvCityAreaStreet<ProvCityAreaStreet> {
	public static final ProvCityAreaStreet dao = new ProvCityAreaStreet();

	private final Integer PROV_LEVEL = 1;
	private final Integer CITY_LEVEL = 2;
	private final Integer AREA_LEVEL = 3;
	private final Integer STREET_LEVEL = 4;

	/**
	 * 获得所有省份
	 * @return
	 */
	public List<ProvCityAreaStreet> getProv() {
		return dao.find(" select * from t_prov_city_area_street where level = ? ", PROV_LEVEL);
	}

	/**
	 * 根据省份id 获取 城市
	 * @param provCode
	 * @return
	 */
	public List<ProvCityAreaStreet> getCity (Integer provCode){
		return getItemByPid(provCode, CITY_LEVEL);
	}

	/**
	 * 根据 城市id 获取 区县
	 * @param cityCode
	 * @return
	 */
	public List<ProvCityAreaStreet> getArea (Integer cityCode){
		return getItemByPid(cityCode, AREA_LEVEL);
	}

	/**
	 * 根据 区县id 获取 街道
	 * @param areaCode
	 * @return
	 */
	public List<ProvCityAreaStreet> getStreet (Integer areaCode){
		return getItemByPid(areaCode, STREET_LEVEL);
	}

	/**
	 * 根据 pid 获取 子集合
	 * @param pid
	 * @return
	 */
	public List<ProvCityAreaStreet> getItemByPid (Integer pid){
		return getItemByPid(pid, null);
	}

	private List<ProvCityAreaStreet> getItemByPid (Integer pid, Integer level){
		if (level != null) {
			return dao.find(" select * from t_prov_city_area_street where parentId = ? and level = ? ", pid, level);
		} else {
			return dao.find(" select * from t_prov_city_area_street where parentId = ?", pid);
		}
	}
}
