package com.wcb.model;

import com.wcb.model.base.BaseRecordPay;

/**
 * Generated by JFinal.
 * 缴费记录
 */
@SuppressWarnings("serial")
public class RecordPay extends BaseRecordPay<RecordPay> {
	public static final RecordPay dao = new RecordPay();
}
