package com.wcb.model;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;
import com.wcb.enums.PayStatusEnum;
import com.wcb.model.base.BaseRecordPay;

import java.util.Date;

/**
 * Generated by JFinal.
 * 缴费记录
 */
@SuppressWarnings("serial")
public class RecordPay extends BaseRecordPay<RecordPay> {
    public static final RecordPay dao = new RecordPay();

    /**
     * 分页
     */
    public Page<RecordPay> paginate(int pageNumber, int pageSize, Integer accountid) {
        return paginate(pageNumber, pageSize, " select t.* ",
                " from t_record_pay t where accountid = " + accountid + " order by paydate desc ");
    }

    /**
     * 获取 账户总 缴纳的 金额总和   单位:分
     *
     * @param accountid
     * @return
     */
    public Integer getSumMoney(Integer accountid) {
        Record obj = Db.findFirst(" select SUM(money) as summoney from t_record_pay where accountid = ? ", accountid);
        if (obj != null && obj.get("summoney") != null) {
            return Integer.valueOf(String.valueOf(obj.get("summoney")));
        }
        return 0;
    }

    private String moneyView;
    private String theorymoneyView;
    private String statusView;

    public String getMoneyView() {
        return getMoney() / 100 + "";
    }

    public void setMoneyView(String moneyView) {
        this.moneyView = moneyView;
    }

    public String getTheorymoneyView() {
        return getTheorymoney() / 100 + "";
    }

    public void setTheorymoneyView(String theorymoneyView) {
        this.theorymoneyView = theorymoneyView;
    }

    public String getStatusView() {
        Integer status = getStatus();
        if (PayStatusEnum.OWE.getCode().equals(status)) {
            return "仍欠费" + (double) (getBalance() / 100) + "元";
        } else if (PayStatusEnum.BALANCE.getCode().equals(status)) {
            return "预存" + (double) (getBalance() / 100) + "元";
        } else if (PayStatusEnum.FINISH.getCode().equals(status)) {
            return "缴清";
        }
        return "";
    }

    public void setStatusView(String statusView) {
        this.statusView = statusView;
    }
}
