package com.wcb.model;

import com.wcb.model.base.BaseRecordSurvey;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RecordSurvey extends BaseRecordSurvey<RecordSurvey> {
	public static final RecordSurvey dao = new RecordSurvey();
}
