package com.wcb.model;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.wcb.enums.PayStatusEnum;
import com.wcb.model.base.BaseRecordPay;

import java.util.Date;

/**
 * Generated by JFinal.
 * 缴费记录
 */
@SuppressWarnings("serial")
public class RecordPay extends BaseRecordPay<RecordPay> {
    public static final RecordPay dao = new RecordPay();

    /**
     * 分页
     */
    public Page<RecordPay> paginate(int pageNumber, int pageSize) {
        return paginate(pageNumber, pageSize, " select t.* ",
                " from t_record_pay t " +
                        " order by paydate desc ");
    }

    /**
     * 获取 账户总 缴纳的 金额总和
     *
     * @param accountid
     * @return
     */
    public Double getSumMoney(Integer accountid) {
        return Db.queryDouble(" select SUM(money) as summoney from t_record_pay where accountid = ? ", accountid);
    }
}
