package com.wcb.model;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.wcb.model.base.BaseRecordSurvey;

import java.util.Date;

/**
 * Generated by JFinal.
 * 抄表记录
 */
@SuppressWarnings("serial")
public class RecordSurvey extends BaseRecordSurvey<RecordSurvey> {
    public static final RecordSurvey dao = new RecordSurvey();

    /**
     * 分页
     */
    public Page<RecordSurvey> paginate(int pageNumber, int pageSize, Integer accountid) {
        return paginate(pageNumber, pageSize, " select t.* ",
                " from t_record_survey t where accountid = " + accountid + " order by readdate desc ");
    }

    /**
     * 获取 账户 最近的一条 抄表信息
     *
     * @param accountid
     * @return
     */
    public RecordSurvey getSurveyByAccountIdForFirst(Integer accountid) {
        return findFirst(" select * from t_record_survey where accountid = ? order by readdate desc ", accountid);
    }

    /**
     * 获取 账户总 产生的费用
     *
     * @param accountid
     * @return
     */
    public Double getSumMoney(Integer accountid) {
        return Db.queryDouble(" select SUM(money) as summoney from t_record_survey where accountid = ? ", accountid);
    }

}
