package com.wcb.model;

import com.jfinal.plugin.activerecord.Page;
import com.wcb.model.base.BaseRoleFunc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleFunc extends BaseRoleFunc<RoleFunc> {
	public static final RoleFunc dao = new RoleFunc();
	public Page<RoleFunc> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select * " , " from t_sys_role_func ");
	}
}
