package com.wcb.model;

import com.wcb.model.base.BaseRoleFunc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleFunc extends BaseRoleFunc<RoleFunc> {
	public static final RoleFunc dao = new RoleFunc();
}
