package com.wcb.model;

import com.wcb.model.base.BaseUser;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.mysql.jdbc.StringUtils;
import java.util.List;

/**
 * Generated by JFinal.
 * 用户 -- 操作员
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User();

	public Page<User> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select * " , " from t_sys_user " +
				"" +
				" order by registerdate desc ,id desc");
	}

	/** 登陆方法  **/
	public User login (String username , String password){

		if(StringUtils.isNullOrEmpty(username) || StringUtils.isNullOrEmpty(password)) return null;

		List<User> list = find("select * from t_sys_user where username ='" + username + "' and password ='" + password+"' ");
		if(list == null || list.isEmpty()){
			return null;
		}else{
			return list.get(0);
		}
	}

	/**用户名是否 不存在**/
	public Boolean usernameNotExist (String username) {
		if(!StringUtils.isNullOrEmpty(username)){
			List<User> list = find("select * from t_sys_user where username ='" + username + "' ");
			if(list == null || list.isEmpty()){
				return true;
			}else{
				return false;
			}
		}else{
			return false;
		}
	}

	/** 批量删除 ids = id,id  **/
	public void deleteList (String ids) {
		if(!StringUtils.isNullOrEmpty( ids )){
			StringBuilder sqlsb = new StringBuilder();
			sqlsb.append("delete from t_sys_user where id in ( ");
			sqlsb.append(ids);
			sqlsb.append(" -1) ");

			Db.update(sqlsb.toString());
		}
	}
}
