package com.wcb.model;

import com.wcb.model.base.BaseUserGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserGroup extends BaseUserGroup<UserGroup> {
	public static final UserGroup dao = new UserGroup();
}
