package com.wcb.model;

import com.wcb.model.base.BaseUser;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.mysql.jdbc.StringUtils;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User();

	public Page<User> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select * " , " from t_sys_user " +
				"" +
				" order by registerdate desc ,id desc");
	}

	/* 登陆方法  */
	public User login (String username , String password){

		if(StringUtils.isNullOrEmpty(username) || StringUtils.isNullOrEmpty(password)) return null;

		List<User> list = dao.find("select * from t_sys_user where username ='" + username + "' and password ='" + password+"' ");
		if(list == null || list.isEmpty()){
			return null;
		}else{
			return list.get(0);
		}
	}

	/*用户名是否 不存在*/
	public Boolean usernameNotExist (String username) {
		if(!StringUtils.isNullOrEmpty(username)){
			List<User> list = dao.find("select * from t_sys_user where username ='" + username + "' ");
			if(list == null || list.isEmpty()){
				return true;
			}else{
				return false;
			}
		}else{
			return false;
		}
	}

	/*public void deleteList (List<Integer> ids) {
        if(ids !=null && ids.size()>0){
            StringBuilder sqlsb = new StringBuilder();
            sqlsb.append("delete from t_sys_user where id in ( ");
            for(Integer id : ids){
                sqlsb.append(id);
                sqlsb.append(",");
            }
            sqlsb.append(" -1) ");

            Db.update(sqlsb.toString());
        }

    }*/
	public void deleteList (String ids) {
		if(!StringUtils.isNullOrEmpty( ids )){
			StringBuilder sqlsb = new StringBuilder();
			sqlsb.append("delete from t_sys_user where id in ( ");
			sqlsb.append(ids);
			sqlsb.append(" -1) ");

			Db.update(sqlsb.toString());
		}
	}
}
