package com.wcb.model;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.mysql.jdbc.StringUtils;
import com.wcb.model.base.BaseUserGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserGroup extends BaseUserGroup<UserGroup> {
	public static final UserGroup dao = new UserGroup();

	public Page<UserGroup> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select * " , " from t_sys_user_group order by sort ");
	}

	public void deleteList(String ids){
		if(!StringUtils.isNullOrEmpty(ids)){
			StringBuilder sqlsb = new StringBuilder();
			sqlsb.append("delete from t_sys_user_group where id in ( ");
			sqlsb.append(ids);
			sqlsb.append(" -1) ");
			Db.update(sqlsb.toString());
		}
	}
}
