package com.sjin.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysUser<M extends BaseSysUser<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setUsername(String username) {
		set("username", username);
	}

	public String getUsername() {
		return get("username");
	}

	public void setPassword(String password) {
		set("password", password);
	}

	public String getPassword() {
		return get("password");
	}

	public void setNickname(String nickname) {
		set("nickname", nickname);
	}

	public String getNickname() {
		return get("nickname");
	}

	public void setEmail(String email) {
		set("email", email);
	}

	public String getEmail() {
		return get("email");
	}

	public void setPhone(String phone) {
		set("phone", phone);
	}

	public String getPhone() {
		return get("phone");
	}

	public void setStatus(Boolean status) {
		set("status", status);
	}

	public Boolean getStatus() {
		return get("status");
	}

	public void setRegisterdate(java.util.Date registerdate) {
		set("registerdate", registerdate);
	}

	public java.util.Date getRegisterdate() {
		return get("registerdate");
	}

	public void setRegistertype(Integer registertype) {
		set("registertype", registertype);
	}

	public Integer getRegistertype() {
		return get("registertype");
	}

	public void setUsertype(Integer usertype) {
		set("usertype", usertype);
	}

	public Integer getUsertype() {
		return get("usertype");
	}

	public void setGroupid(Integer groupid) {
		set("groupid", groupid);
	}

	public Integer getGroupid() {
		return get("groupid");
	}

}
