package com.sjin.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTimelineMore<M extends BaseTimelineMore<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setTid(Integer tid) {
		set("tid", tid);
	}

	public Integer getTid() {
		return get("tid");
	}

	public void setTxt(String txt) {
		set("txt", txt);
	}

	public String getTxt() {
		return get("txt");
	}

	public void setSort(Integer sort) {
		set("sort", sort);
	}

	public Integer getSort() {
		return get("sort");
	}

}
