package com.sjin.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDoubleballRecord<M extends BaseDoubleballRecord<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setPeriod(Integer period) {
		set("period", period);
	}

	public Integer getPeriod() {
		return get("period");
	}

	public void setValue(Integer value) {
		set("value", value);
	}

	public Integer getValue() {
		return get("value");
	}

	public void setType(Integer type) {
		set("type", type);
	}

	public Integer getType() {
		return get("type");
	}

}
