package com.wcb.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCommunity<M extends BaseCommunity<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setProvince(java.lang.Integer province) {
		set("province", province);
	}

	public java.lang.Integer getProvince() {
		return get("province");
	}

	public void setCity(java.lang.Integer city) {
		set("city", city);
	}

	public java.lang.Integer getCity() {
		return get("city");
	}

	public void setArea(java.lang.Integer area) {
		set("area", area);
	}

	public java.lang.Integer getArea() {
		return get("area");
	}

	public void setStreet(java.lang.Integer street) {
		set("street", street);
	}

	public java.lang.Integer getStreet() {
		return get("street");
	}

}
