package com.wcb.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setNickname(java.lang.String nickname) {
		set("nickname", nickname);
	}

	public java.lang.String getNickname() {
		return get("nickname");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setStatus(java.lang.Boolean status) {
		set("status", status);
	}

	public java.lang.Boolean getStatus() {
		return get("status");
	}

	public void setRegisterdate(java.util.Date registerdate) {
		set("registerdate", registerdate);
	}

	public java.util.Date getRegisterdate() {
		return get("registerdate");
	}

	public void setRegistertype(java.lang.Integer registertype) {
		set("registertype", registertype);
	}

	public java.lang.Integer getRegistertype() {
		return get("registertype");
	}

	public void setUsertype(java.lang.Integer usertype) {
		set("usertype", usertype);
	}

	public java.lang.Integer getUsertype() {
		return get("usertype");
	}

	public void setGroupid(java.lang.Integer groupid) {
		set("groupid", groupid);
	}

	public java.lang.Integer getGroupid() {
		return get("groupid");
	}

}
