package com.wcb.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAccountEquipment<M extends BaseAccountEquipment<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setAccountid(java.lang.Integer accountid) {
		set("accountid", accountid);
	}

	public java.lang.Integer getAccountid() {
		return get("accountid");
	}

	public void setEquipmentid(java.lang.Integer equipmentid) {
		set("equipmentid", equipmentid);
	}

	public java.lang.Integer getEquipmentid() {
		return get("equipmentid");
	}

	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}

	public java.util.Date getCreatedate() {
		return get("createdate");
	}

	public void setInvaliddate(java.util.Date invaliddate) {
		set("invaliddate", invaliddate);
	}

	public java.util.Date getInvaliddate() {
		return get("invaliddate");
	}

	public void setStatus(java.lang.Boolean status) {
		set("status", status);
	}

	public java.lang.Boolean getStatus() {
		return get("status");
	}

}
