package com.wcb.model.basicdata;
import com.wcb.model.base.BaseAccount;
/**
 * Generated by shijing.guan
 */
@SuppressWarnings("serial")
public class Account extends BaseAccount<Account> {
	public static final Account dao = new Account();
}
