package com.wcb.model.basicdata;
import com.wcb.model.base.BaseAccountEquipment;
/**
 * Generated by shijing.guan
 */
@SuppressWarnings("serial")
public class AccountEquipment extends BaseAccountEquipment<AccountEquipment> {
	public static final AccountEquipment dao = new AccountEquipment();
}
