package com.wcb.model.basicdata;
import com.wcb.model.base.BaseCommunity;
/**
 * Generated by shijing.guan
 */
@SuppressWarnings("serial")
public class Community extends BaseCommunity<Community> {
	public static final Community dao = new Community();
}
