package com.wcb.model.basicdata;
import com.wcb.model.base.BaseDistrictUser;
/**
 * Generated by shijing.guan
 */
@SuppressWarnings("serial")
public class DistrictUser extends BaseDistrictUser<DistrictUser> {
	public static final DistrictUser dao = new DistrictUser();
}
