package com.wcb.model.basicdata;
import com.wcb.model.base.BaseDistrict;
/**
 * Generated by shijing.guan
 */
@SuppressWarnings("serial")
public class District extends BaseDistrict<District> {
	public static final District dao = new District();
}
