package com.wcb.model.basicdata;
import com.wcb.model.base.BaseEquipment;
/**
 * Generated by shijing.guan
 */
@SuppressWarnings("serial")
public class Equipment extends BaseEquipment<Equipment> {
	public static final Equipment dao = new Equipment();
}
