package com.wcb.model.basicdata;
import com.wcb.model.base.BaseProvCityAreaStreet;
/**
 * Generated by shijing.guan
 */
@SuppressWarnings("serial")
public class ProvCityAreaStreet extends BaseProvCityAreaStreet<ProvCityAreaStreet> {
	public static final ProvCityAreaStreet dao = new ProvCityAreaStreet();
}
