package com.wcb.model.basicdata;
import com.wcb.model.base.BaseRecordSurvey;
/**
 * Generated by shijing.guan
 */
@SuppressWarnings("serial")
public class RecordSurvey extends BaseRecordSurvey<RecordSurvey> {
	public static final RecordSurvey dao = new RecordSurvey();
}
