package com.wcb.model.basicdata;
import com.wcb.model.base.BaseRecordPay;
/**
 * Generated by shijing.guan
 */
@SuppressWarnings("serial")
public class RecordPay extends BaseRecordPay<RecordPay> {
	public static final RecordPay dao = new RecordPay();
}
