package com.wcb.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRecordPay<M extends BaseRecordPay<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setAccountid(Integer accountid) {
		set("accountid", accountid);
	}

	public Integer getAccountid() {
		return get("accountid");
	}

	public void setPaydate(java.util.Date paydate) {
		set("paydate", paydate);
	}

	public java.util.Date getPaydate() {
		return get("paydate");
	}

	public void setMoney(Integer money) {
		set("money", money);
	}

	public Integer getMoney() {
		return get("money");
	}

	public void setSurveyid(Integer surveyid) {
		set("surveyid", surveyid);
	}

	public Integer getSurveyid() {
		return get("surveyid");
	}

	public void setStatus(Boolean status) {
		set("status", status);
	}

	public Boolean getStatus() {
		return get("status");
	}

	public void setBalance(Integer balance) {
		set("balance", balance);
	}

	public Integer getBalance() {
		return get("balance");
	}

}
