package com.wcb.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEquipment<M extends BaseEquipment<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setCode(String code) {
		set("code", code);
	}

	public String getCode() {
		return get("code");
	}

	public void setType(Integer type) {
		set("type", type);
	}

	public Integer getType() {
		return get("type");
	}

	public void setManufacturers(String manufacturers) {
		set("manufacturers", manufacturers);
	}

	public String getManufacturers() {
		return get("manufacturers");
	}

	public void setModel(String model) {
		set("model", model);
	}

	public String getModel() {
		return get("model");
	}

}
