package com.wcb.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCommunity<M extends BaseCommunity<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setProvince(Integer province) {
		set("province", province);
	}

	public Integer getProvince() {
		return get("province");
	}

	public void setCity(Integer city) {
		set("city", city);
	}

	public Integer getCity() {
		return get("city");
	}

	public void setArea(Integer area) {
		set("area", area);
	}

	public Integer getArea() {
		return get("area");
	}

	public void setStreet(Integer street) {
		set("street", street);
	}

	public Integer getStreet() {
		return get("street");
	}

}
