package com.wcb.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProvCityAreaStreet<M extends BaseProvCityAreaStreet<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setCode(String code) {
		set("code", code);
	}

	public String getCode() {
		return get("code");
	}

	public void setParentId(String parentId) {
		set("parentId", parentId);
	}

	public String getParentId() {
		return get("parentId");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setLevel(Boolean level) {
		set("level", level);
	}

	public Boolean getLevel() {
		return get("level");
	}

}
