package com.wcb.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDistrictUser<M extends BaseDistrictUser<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setUserid(Integer userid) {
		set("userid", userid);
	}

	public Integer getUserid() {
		return get("userid");
	}

	public void setDistid(Integer distid) {
		set("distid", distid);
	}

	public Integer getDistid() {
		return get("distid");
	}

}
